### PR TITLE
Update docs to support npgsql 7

### PR DESCRIPTION
**Pull request by fbjerggaard**
Related to main PR: Eventuous/eventuous#183

### CODE REVIEW

**Comment by alexeyzimarev** [comment]
Not sure how this is going to work? The store needs `GetConnection`, it won't accept `NpgsqlDataSourceBuilder`.

**Comment by alexeyzimarev** [comment]
That's what I came up with

```
var ds = new NpgsqlDataSourceBuilder(connectionString).Build();
NpgsqlConnection GetConnection() => ds.CreateConnection();
builder.Services.AddSingleton(GetConnection());
builder.Services.AddAggregateStore<PostgresStore>();
```

**Comment by fbjerggaard** [comment]
The store accepts the `NpgsqlDataSourceBuilder` once the related PR has been implemented. It needs to (as far as I understand it) be a `NpgsqlDataSourceBuilder` and not a connection since the typemapping needs to be done on the builder itself

**Comment by alexeyzimarev** [comment]
I see. I suggest we close this one, I added some words about using the builder to the new version, which has a different folder structure, so it would be hard to merge.

**Comment by fbjerggaard** [comment]
That's fair - let's close this one then.

**Pull request closed without merging**
